### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by jimbo1qaz** [bbugyi200/funky#143]
```
~ ❯❯❯ funky
Traceback (most recent call last):
  File "/home/jimbo1qaz/.local/bin/funky", line 6, in <module>
    from funky.app import main
  File "/home/jimbo1qaz/.local/venvs/pyfunky/lib/python3.6/site-packages/funky/app.py", line 11, in <module>
    from funky import commands
  File "/home/jimbo1qaz/.local/venvs/pyfunky/lib/python3.6/site-packages/funky/commands.py", line 11, in <module>
    from six import string_types
ModuleNotFoundError: No module named 'six'
```

six is not present in clean Python 3.6/3.7 virtualenv/venv (via poetry or pipsi). Maybe add 'six' to setup.py `install_requires`?

Installing "six" alone seems to make "funky" CLI not throw an exception immediately.

**Comment by bbugyi200** [comment]
Thank you for reporting this. I believe 39333fb9e0ea3f02b448ba4e33777777ca6d5b94 should fix this. I released a new version (v.3.3.1) that includes this patch.
